### ISSUE TITLE
方向键上下和左右同时键控制进度条是否合适

### ISSUE THREAD

**Issue by wood-j** [chiflix/splayerx#1197]
RT
方向键左右键控制进度条符合大部分播放器使用习惯
但是上下键通常是控制音量
相关信息：
Macos 10.14.6
SPlayer 4.7.0

**Comment by huzhenghui37** [comment]
感谢反馈，mac上有很多调节音量的方式，尤其是笔记本电脑，而且老版本也是同样的设计，尊重一下传统。目前上下健是调节1分钟，左右键是5秒，不知道您留意到了没有？感谢。

wood-j <notifications@github.com>于2019年12月7日 周六17:14写道：
