### ISSUE TITLE
我发现了影片时长判断的bug这会影响到收费

### ISSUE THREAD

**Issue by jieyuanmao** [chiflix/splayerx#1313]

**Comment by jieyuanmao** [comment]
请尽快查看我发给贵公司的邮件   收件地址是support@splayer.org

我是支付成功后跳转回商户页面的时候无意中发现这个BUG
我已经给贵公司在邮件中详细描写了触发bug的操作流程
希望能得到重视
并且可以解决我支付成功但没有给我翻译字幕的问题。

**Comment by ipy** [comment]
已通过邮件沟通~
