### ISSUE TITLE
播放4k视频相当卡，一顿一顿的

### ISSUE THREAD

**Issue by cat9** [chiflix/splayerx#239]
我使用你们的0.0.3release版本，播放下面描述的视频，卡顿十分厉害，基本上播放一秒卡顿几秒。
但我使用win10自带播放器或者potplayer播放非常顺畅。

一下是我从potplayer获取出来的相关信息
[视频信息]
视频编码： AVC1 - 内置 FFmpeg 解码器(h264, Thread Frame)
输入格式： AVC1(24 bits)
输入尺寸： 4096 x 2160(1.9:1)
输出格式： YV12(12 bits)
输出尺寸： 4096 x 2160(1.9:1)
帧率：23.98
BitRate: 59804kbps

[CPU]
CPU #0: 3193MHz, Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, Intel64 Family 6 Model 60 Stepping 3
CPU #1: 3193MHz, Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, Intel64 Family 6 Model 60 Stepping 3
CPU #2: 3193MHz, Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, Intel64 Family 6 Model 60 Stepping 3
CPU #3: 3193MHz, Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, Intel64 Family 6 Model 60 Stepping 3
Instruction set: MMX MMXEXT MMX2 SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AVX AVX2 FMA3 CMOV BMI1 BMI2 

[OS]
Version: Windows 10 or Later(10.0)
Bits: Native 64
DirectX: 9.0c(4.09.00.0904)
Direct3D 9Ex: OK

**Comment by huzhenghui37** [comment]
非常感谢反馈，0.0.3已经是非常旧的临时打包版本，Electron 定制内核已经更新，但还没有发布，可以等到11月底的新版本。性能bug解决，速度已经有巨大提升，感谢。

**Comment by huzhenghui37** [comment]
另外，以后也可以到 https://splayer.nolt.io/ 提出反馈意见，未来应该会放到产品官网和系统菜单入口。
