### ISSUE TITLE
希望能加快进度和后期接口

### ISSUE THREAD

**Issue by yikiyuan** [chiflix/splayerx#283]
希望能加快进度，先发布一个基础能够使用的播放器（包含基础功能和字幕功能即可），现在只有播放功能没有字幕功能，实际想测试使用也存在困难。
可考虑加入后期编码接口，后期另外增加解码包或单独发布某些编码的解码包对接，减低后期成本开发。
来自使用多年的splay fans

**Comment by huzhenghui37** [comment]
感谢关注和建议，下周会有一个新的打包版本发布供下周测试，其中包含了比较完整基础和字幕功能，非常感谢，希望一直听到你的反馈和批评。

**Comment by uptonking** [comment]
射手影音用起来还是熟悉的味道，用了很多年了很喜欢，最爱的一个功能是在视频右上角拖拉可以等比例放大缩小视频画面，加油
