### ISSUE TITLE
版本4.0.1的窗口移动等其他问题

### ISSUE THREAD

**Issue by yikiyuan** [chiflix/splayerx#287]
版本为4.0.1，右键如果选择菜单按住鼠标左键会引起窗口进行移动操作。界面的移动和调整大小可以进行优化，不然控制起来有点不顺心。
直接打开播放器（显示最近播放）的那个界面，可以加入右键的设置事件，方便日后直接设置播放器的选项。
播放的时候使用前进后退比较卡顿（暂时发现的是H265的视频比较明显）别的视频直接拖拉或者直接播放中间时间的也会卡顿。
希望解码的格式继续增加，暂时貌似对音频还不能播放。
切换音轨方式还不能使用，切换还没任何效果。

**Comment by huzhenghui37** [comment]
非常感谢反馈，我们会每一条都记录一下，目前解码格式正在继续增加，H265的性能问题也在解决，新的跨平台构架在windows上问题也比较多。另外，在 feedback.splayer.org 也可以提反馈唷，哈。
