### ISSUE TITLE
建议考虑安卓系统（播放机）和电视UI操作

### ISSUE THREAD

**Issue by myselfghost** [chiflix/splayerx#3]
现如今，买高清播放机的用户还真不少，大部分播放机也是基于安卓系统做的，建议有安卓的版本。并且使用场景是链接高清屏幕或投影，所以操作UI上建议有考虑遥控器的便捷操作。

**Comment by huzhenghui37** [comment]
嗯嗯，团队会考虑类似需求的。

**Comment by myselfghost** [comment]
谢谢，那其实还有个附加需求就是，可以支持samba和 nfs  浏览媒体，播放媒体。
