### ISSUE TITLE
增加对mkv大文件支持

### ISSUE THREAD

**Issue by nsb2006** [chiflix/splayerx#327]
10.8G的mkv文件无法播放，3.5G的可以，请考虑支持大文件mkv播放，谢谢。

**Comment by huzhenghui37** [comment]
非常感谢提出反馈，想具体问一下，无法播放时具体什么现象，是无法打开？窗口黑屏？还是没有反应？还是播放非常非常卡？有没有什么报错信息？或者能否提供您播放的文件的下载信息，我们下载之后测试一下，否则很难判断是什么原因造成的。非常感谢。

**Comment by nsb2006** [comment]
视频文件磁力链接：magnet:?xt=urn:btih:b560f3e9fdb7bb48d690d8a9cb1da058cc527437&dn=%E3%80%90www.gaoqing.tv%E3%80%91%E9%BE%99%E7%8C%AB [%E5%9B%BD%E7%B2%A4%E8%8B%B1%E6%97%A5%E5%9B%9B%E9%9F%B3%E8%BD%A8 %E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95] My.Neighbor.Totoro.1988.1080p.BluRay.x264.Tetra.Audio.AC3-HDCh

文件名：My.Neighbor.Totoro.1988.1080p.BluRay.x264.DTS-WiKi.mkv，文件大小：10.8G

播放时播放器黑屏，无法操作（右键和各功能菜单均无法操作）。
