### ISSUE TITLE
Support chromecast projecting

### ISSUE THREAD

**Issue by soleo** [chiflix/splayerx#5]
love to be able to use it for playing on TV with chrome-cast

https://github.com/thibauts/node-castv2-client/blob/master/README.md

**Comment by ymmuse** [comment]
The feature doesn't need any third-party. Player based on Electron that has had cast client function.

**Comment by soleo** [comment]
ref https://github.com/electron/electron/issues/869 Doesn't look like Electron has cast client. There are discussions about it though.

**Comment by ymmuse** [comment]
The chromecast has been integrated with UI of chromium. if it integrates with any other front-end from [chromecast](https://chromium.googlesource.com/chromium/src/+/master/chromecast). That's not easy to support the feature. Too many works need to do but Contributions are very welcome.
