### ISSUE TITLE
[建议]为自动播放列表的功能增加开关

### ISSUE THREAD

**Issue by ntbps** [chiflix/splayerx#610]
播放文件时会把当前目录下的其他文件加入播放列表, 这是一个很好的行为.
然而有时候用户的真实需求是: 播放完毕后停止, 而非播放结束后自动跳到列表中的下一个视频.
所以, 建议在设置中增加一个相关的开关.

**Comment by huzhenghui37** [comment]
很像了解一下这个需求的背后，为什么想播完一集就停下呢？是要上个洗手间？

**Comment by ntbps** [comment]
好吧, 我也发现这是个伪需求了. 
我用 ffmpeg 生成简短的视频(1-8s), 在 macOSX 把 Splayer 设置成默认媒体播放器, 当用到 `open ${path_to_a_video_file}`时, 经常是画面一闪而过.
`暂停+快进+快退`在手速够快的时候可以满足我的需求, 后来我自己加了 **continuousPlayback**  的功能时, 才发现 **singleCycle** 也能在一定程度上满足我的需求.
