### ISSUE TITLE
Pressing the space bar doesn't pause the play on MacOSx 10.14.6

### ISSUE THREAD

**Issue by isheebo** [chiflix/splayerx#859]
When playing a video locally in fullscreen mode, pressing `space` doesn't pause the video.
Instead to pause the video, one would have to first exit fullscreen mode and then pause the playback.

**Comment by isheebo** [comment]
One would have to first toggle between having the player in fullscreen and having the player in minimized mode before successfully pausing or restarting playback

**Comment by ipy** [comment]
Thank you for your feedback. Unfortunately we are not able to reproduce it on our side. Could you provide the following information:
* The detailed steps to reproduce the issue
* Version of SPlayer you are using
* Is it related to a specific video file? If so, could you send the file to support@splayer.org for further investigation?

**Comment by ipy** [comment]
Closed as inactive, feel free to reopen the issue if you have further information.
