### ISSUE TITLE
problem with .srt subtitles 

### ISSUE THREAD

**Issue by ZeraW** [chiflix/splayerx#898]
i tried the new Splayer and when i tired to use subtitle with .srt format it says " subtitle type unsupported " 
i really like the new ui so please fix it

**Comment by surpassing** [comment]
Could you please attach a copy of the SRT file here: https://feedback.splayer.org/282

**Comment by ZeraW** [comment]
> Could you please attach a copy of the SRT file here: https://feedback.splayer.org/282

i did upload the srt file sorry for the delay

**Comment by surpassing** [comment]
@ZeraW The SRT issue has been fixed in v4.4.0-beta.2. (https://github.com/chiflix/splayerx/releases) 

We will release the stable version later.
