### ISSUE TITLE
[BUG] 播放某些下载未完全的视频后再打开任意视频大约 3-5 秒后应用崩溃

### ISSUE THREAD

**Issue by Caldis** [chiflix/splayerx#921]
### 问题描述
我本地有一个视频未下载完全，只要播放到这个视频的某个时间点播放器就会卡死，只能强制退出。
而在强制退出播放器后再打开任意正常视频大概 3-5 秒后播放器也会继续黑屏卡死，即使暂停视频也是一样，只有重启电脑能解决这个问题。

### 应用版本
4.2.2

### 系统版本
Windows 10 x64 18912

**Comment by surpassing** [comment]
方便加QQ群(846084152)发一下视频文件吗，这边需要本地复现看下报错信息，谢谢。

**Comment by Caldis** [comment]
@surpassing 加了貌似没人回应，我传到百度网盘了
链接: https://pan.baidu.com/s/1rMJVD3pLMA_z6dnmC2flAQ 提取码: 6fgh

**Comment by Caldis** [comment]
这份视频我用 Potplayer 或者 Windows10 自带的播放器打开都是正常的，视频的大部分都应该下载完全了

**Comment by surpassing** [comment]
@Caldis 已在群里回复
